resources:
  - name: simplehelmChart
    type: HelmChart
    configuration:
      sourceArtifactory: demoArt
      repository: helm
      chart: simplehelm
      version: 0.0.0

  - name: simplehelmRepo_chart
    type: GitRepo
    configuration:
      gitProvider: markg_github
      path: markgalpin/simplehelm
      files:
        include: "simplehelm.*"

  - name: simplehelmRepo_docker
    type: GitRepo
    configuration:
      gitProvider: markg_github
      path: markgalpin/simplehelm
      files:
        include: "Dockerfile|server.js|package.json"

  - name: simplehelmDockerImage1
    type: Image
    configuration:
      registry: demoArt
      sourceRepository: docker-local
      imageName: 35.224.208.129:8082/docker-local/simplehelm
      imageTag: latest

pipelines:
  - name: helm_full_flow
    steps:
      - name: dockerBuildPush
        type: Bash
        configuration:
          integrations:
            - name: demoArt
          inputResources:
            - name: simplehelmRepo_docker
          outputResources:
            - name: simplehelmDockerImage1
        execution:
          onExecute:
            - pushd $res_simplehelmRepo_docker_resourcePath
            - docker build -t 35.224.208.129:8082/docker-local/simplehelm:$run_number .
            - jfrog rt docker-push 35.224.208.129:8082/docker-local/simplehelm:$run_number docker-local --build-name=$pipeline_name --build-number=$run_number
            - write_output simplehelmDockerImage1 "imageTag=$run_number"

      - name: publish_helm_chart
        type: HelmPublish
        configuration:
          inputResources:
            - name: simplehelmRepo_chart
          outputResources:
            - name: simplehelmChart
          chartPath: ./simplehelm

      - name: deploy_helm_chart
        type: HelmDeploy
        configuration:
          integrations:
            - name: testkube
            - name: jfroggcmpkey
          inputResources:
            - name: simplehelmChart
            - name: simplehelmDockerImage1
          releaseName: simplehelm
          valueFilePaths:
            - values.yaml
        execution:
          onStart:
            - echo $int_jfroggcmpkey_jsonKey > mykey.json
            - gcloud auth activate-service-account pipelinesdemo1@jfrog-gc-mp.iam.gserviceaccount.com --key-file=mykey.json
            - helm init --tiller-namespace default

